import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cn } from './lib/utils'
import Navbar from '@/components/Navbar'
import Providers from '@/components/Providers' 
import Loglib from "@loglib/tracker/react";
import { ThemeProvider } from '@/components/theme-provider'
// import { ThemeProvider } from '@/components/theme-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Scribe Ai',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" 
      className='dark'>
      <Providers>
        <body 
        className={cn(
          'min-h-screen font-sans antialiased gradient',
          inter.className
        )}>
          <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
            
          
              <Navbar />
              {children}
              <Loglib
                    config={{
                        id: "meta",
                        consent: "granted",
                    }}
                />
          </ThemeProvider>
        </body>
      </Providers>
    </html>
  )
}
